
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 19 02:32:17 VET 2017
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONDICIONES = 4;
  public static final int NUMERO = 46;
  public static final int TURN = 39;
  public static final int DOBLERAYA = 35;
  public static final int OP_MAYOR = 30;
  public static final int OP_PRODUCTO = 18;
  public static final int POP = 37;
  public static final int UMINUS = 24;
  public static final int SIMBOLO = 13;
  public static final int PUSH = 36;
  public static final int GENERATRIZ = 7;
  public static final int MATRIZ = 6;
  public static final int OP_NOT = 33;
  public static final int OP_MAYOR_IG = 29;
  public static final int OP_AND = 25;
  public static final int FIN = 5;
  public static final int GRAMATICA = 3;
  public static final int OP_POTENCIA = 21;
  public static final int TYPE = 44;
  public static final int LP = 42;
  public static final int NOM_SIMBOL = 15;
  public static final int TITULO = 2;
  public static final int RP = 43;
  public static final int MOV = 38;
  public static final int OP_DIF = 32;
  public static final int OP_MOD = 20;
  public static final int EOF = 0;
  public static final int OP_MENOR_IG = 28;
  public static final int OP_DIVISION = 19;
  public static final int PASOS = 9;
  public static final int error = 1;
  public static final int COMA = 41;
  public static final int OP_LOG = 22;
  public static final int OP_OR = 26;
  public static final int OP_RESTA = 17;
  public static final int OP_ASSIGN = 23;
  public static final int DOBLESALTO = 45;
  public static final int FLECHA = 34;
  public static final int VALOR = 12;
  public static final int PROBABILIDAD = 14;
  public static final int OP_IGUAL = 31;
  public static final int POSICION = 11;
  public static final int ANGULO = 10;
  public static final int PARAMETRO = 8;
  public static final int OP_SUMA = 16;
  public static final int NOM_PARAM = 47;
  public static final int DOSPTS = 40;
  public static final int OP_MENOR = 27;
}

