
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 13 12:32:57 VET 2017
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONDICIONES = 5;
  public static final int NUMERO = 44;
  public static final int TURN = 37;
  public static final int OP_MAYOR = 29;
  public static final int DOBLERAYA = 33;
  public static final int OP_PRODUCTO = 19;
  public static final int POP = 35;
  public static final int UMINUS = 25;
  public static final int SIMBOLO = 14;
  public static final int PUSH = 34;
  public static final int GENERATRIZ = 8;
  public static final int MATRIZ = 7;
  public static final int COMENTARIOS = 3;
  public static final int OP_AND = 26;
  public static final int FIN = 6;
  public static final int GRAMATICA = 4;
  public static final int OP_POTENCIA = 22;
  public static final int TYPE = 42;
  public static final int LP = 40;
  public static final int NOM_SIMBOL = 16;
  public static final int TITULO = 2;
  public static final int RP = 41;
  public static final int MOV = 36;
  public static final int OP_DIF = 31;
  public static final int OP_MOD = 21;
  public static final int EOF = 0;
  public static final int OP_DIVISION = 20;
  public static final int PASOS = 10;
  public static final int error = 1;
  public static final int COMA = 39;
  public static final int OP_LOG = 23;
  public static final int OP_OR = 27;
  public static final int OP_RESTA = 18;
  public static final int OP_ASSIGN = 24;
  public static final int DOBLESALTO = 43;
  public static final int FLECHA = 32;
  public static final int VALOR = 13;
  public static final int PROBABILIDAD = 15;
  public static final int OP_IGUAL = 30;
  public static final int POSICION = 12;
  public static final int ANGULO = 11;
  public static final int PARAMETRO = 9;
  public static final int OP_SUMA = 17;
  public static final int NOM_PARAM = 45;
  public static final int DOSPTS = 38;
  public static final int OP_MENOR = 28;
}

